global:
  input_dir: "Data/Data_raw"
  output_dir: "Data/Data_augmented"
  prefix: "aug_autoaugment"
  input_format: "png"
  output_format: "png"
augmentations:
  - augmentation: autoaugment
    args: {}
    portion: 0.3
