global:
  input_dir: "Data/Data_raw"
  output_dir: "Data/Data_augmented"
  prefix: "aug_rotation"
  input_format: "png"
  output_format: "png"
augmentations:
  - augmentation: rotation
    args:
      angle: 45
    portion: 0.3
