global:
  input_dir: "Data/Data_raw"
  output_dir: "Data/Data_augmented"
  prefix: "aug_tileswap"
  input_format: "png"
  output_format: "png"
augmentations:
  - augmentation: tileswap
    args:
      n: 12
      strategy: neighbor
      m: 6
    portion: 0.7
